# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindYourFace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'Firebase/Messaging'
  # Pods for FindYourFace

  target 'FindYourFaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
